@startuml library_components

!if %not(%variable_exists("$COMPONENTS"))
    !include ./Templates/Components2.cuml
!endif

title Components diagram of the library math_extra_lib. $generated()

$library(math_extra_lib) {
    !if $is_not_defined("$VECTORS_MATRICES_COMPONENTS")
        !include ./vectors_matrices/vectors_matrices_components.iuml
    !endif
    
    !if $is_not_defined("$POLYNOMIAL_COMPONENTS")
        !include ./polynomial/polynomial_components.iuml
    !endif
    
    !if $is_not_defined("$SPECIAL_FUNCTIONS")
        !include ./special_functions/special_functions_components.iuml
    !endif
    
    polynomial <--- special_functions
    
    !if $is_not_defined("$MATRIX_SOLVER")
        !include ./matrix_solver/matrix_solver_components.iuml
    !endif
    
    matrix_solver ----> vectors_matrices
}
@enduml